apiVersion: skaffold/v2beta27
kind: Config
build:
  artifacts:
    - image: app
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: skaffolddb
        repo: https://charts.bitnami.com/bitnami
        remoteChart: postgresql
        version: 11.1.19
        wait: true
        setValues:
          auth.postgresPassword: skaffold
          auth.database: skaffold
      - name: app
        chartPath: resources/app
        artifactOverrides:
          image: app
portForward:
  - resourceType: deployment
    resourceName: app
    namespace: default
    port: 8080
